- name: ec2instance-playbook
  hosts: host
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: update
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Create a docker network
      docker_network:
        name: test
    - name: Re-create a MySQL container
      docker_container:
        name: nhatanh-mysql
        image: mysql
        networks:
          - name: test
            aliases:
              - test
        env:
          MYSQL_ROOT_PASSWORD: 123456a@
          MYSQL_DATABASE: db_example
        detach: true
        state: started
        recreate: yes
        exposed_ports:
          - 3306
        pull: true
        comparisons:
          image: strict
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ./script
        dest: /home/ubuntu/script
        owner: ubuntu
        group: ubuntu
    - name: SLEEP now !!!
      shell: sleep 15 && sudo docker exec -i nhatanh-mysql mysql --user=root --password=123456a@ < script

    - name: Re-create a NodeJS container
      docker_container:
        name: nhatanh-nodejs
        image: donhatanh2000/nodejs
        networks:
          - name: test
            aliases:
              - test
        state: started
        recreate: yes
        exposed_ports:
          - 8080
        detach: true
        published_ports:
          - 8080:8080
        pull: true
        comparisons:
          image: strict

    - name: Re-create a Nginx container
      docker_container:
        name: nhatanh-nginx
        image: nginx
        networks:
          - name: test
            aliases:
              - test
        detach: true
        state: started
        recreate: yes
        exposed_ports:
          - 80
        published_ports:
          - 80:80
        pull: true
        comparisons:
          image: strict

    - name: Copy nginx.conf to Nhatanh Nginx container
      docker_copy:
        src: ./nginx.conf
        dest: /etc/nginx/nginx.conf
        container: nhatanh-nginx

    - name: Restart Nhatanh Nginx container
      docker_container:
        name: nhatanh-nginx
        state: restarted

    - name: Prune everything
      community.docker.docker_prune:
        containers: true
        images: true

        
